### ISSUE TITLE
Add Support for IP Ranges

### ISSUE THREAD

**Issue by davekempe** [sol1/icingaweb2-module-netbox#12]
We want to map IP Ranges custom fields to Icinga zones. Please add support into Importsource.php for IP Ranges. Possibly more problems to come after that, but lets start there.

**Comment by davekempe** [comment]
The current support is great. Can we add support for Services now, so I can set their check source correctly?

**Comment by sol1-matt** [comment]
> The current support is great. Can we add support for Services now, so I can set their check source correctly?

There is a service mode, though individual services have an ip array so you could get a service in multiple zones. 

I think we need to define what else is required here in more detail.

**Comment by davekempe** [comment]
This is done!
