### ISSUE TITLE
Add support for FHRP groups

### ISSUE THREAD

**Issue by davekempe** [sol1/icingaweb2-module-netbox#13]
We have a bunch of VIPs and would love to be able to import the FHRP groups as Hosts in Icinga. This would allow us to create Host objects, and then apply rules to monitor these vips as "virtual" hosts. Would be neat to be able then have custom vars which showed the "real" machines associated with the fhrp group.

**Comment by sol1-matt** [comment]
Devices and VM's can have VIPs assigned to them via FHRP Groups in Netbox. 

Add the ability to import FHRP Groups and associate them with Devices and VM's is required here.

**Comment by sol1-matt** [comment]
IP Addresses link to FHRP's via `assigned_object`
FHRP's link to IP Addresses via `ip_addresses`

**Comment by sol1-matt** [comment]
Ready for testing as of commit 1c9944de99f3b3c6cf9eb8f949304923fc38c941
There has been no linking
This is purely for creation of Icinga Hosts Objects for VIP's

There is the option to split ip addresses into separate rows, the description + ip address is used to make unique hostnames

**Comment by sol1-matt** [comment]
Moved split ip's to primary_ip_address from ip_address so range lookup would work 000a8b55261bc9466c749723d09900a6177bc14d
