### ISSUE TITLE
Connecting to https url with a self-signed certificate

### ISSUE THREAD

**Issue by iliasbarthelemy** [sol1/icingaweb2-module-netbox#19]
Hello, 
I' trying to connect to my netbox instance using a a self signed certificate.

I'm getting the error:
This Import Source failed when last checked at 2022-09-19 16:15:47: get https://netbox.xxxx.com/api/ipam/services/?status=active&limit=1000: status 0 SSL: unable to obtain common name from peer certificate

After some googling I added
`curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);` to line 29 of Netbox.php

But now i'm getting the following error:
This Import Source failed when last checked at 2022-09-19 16:18:29: get https://netbox.xxxxxxx.com/api/ipam/services/?status=active&limit=1000: status 403

Can anyone help me out ?
The token and API url are correct.

Best regards

**Comment by sol1-matt** [comment]
403 is a auth error so it looks like you've fixed the first problem. For auth errors I'd check the following

* the url is right `https://netbox.example.com/api`, no trailing slash is important (your url's above look correct)
* the token is correct
* the user that the token is from has permissions to access objects, (specifically services for the url's above)

If that doesn't work I'd look at testing netbox using `curl` on the command line. This helps prove Netbox is functioning and the switches used can help figuring out what is required to get it working.

**Comment by iliasbarthelemy** [comment]
Indeed, the problem was with Netbox.
