### ISSUE TITLE
Import only active objects

### ISSUE THREAD

**Issue by ollytom** [sol1/icingaweb2-module-netbox#2]
A feature in the Netbox PHP library to only import objects from Netbox with status "Active". 
At HTTP request means adding url param "status=active"

At UI can be exposed as a checkbox when selecting the type of object to import. For example:

Type of object to import: Devices
Import only "Active"? : true/false

This will mean commit 7aa6cc06f2c73 (not actually done by my username but git username set on a server...) will be reverted

**Comment by davekempe** [comment]
this is resolved a long time ago
