### ISSUE TITLE
Ability to import racks

### ISSUE THREAD

**Issue by willfurnell** [sol1/icingaweb2-module-netbox#28]
Hi,
It doesn't seem like this module currently supports importing racks from Netbox (but almost everything else). Is that something that would be possible to support please?

Thanks,
Will.

**Comment by sol1-matt** [comment]
@willfurnell it is fairly straight forward to add other objects from Netbox. 

Having a quick look at the Netbox objects I can't see much point in adding Rack Role, it doesn't appear to contain any unique information that wouldn't be available on the rack itself. 

I can't think of a use case for importing Rack Reservation at the current point in time either. 

Based on these assumptions I'm going to add rack only at this stage unless there is a use case for importing the other data so we limit UI clutter.

**Comment by sol1-matt** [comment]
Seems racks can have duplicate names in them, no fix in code in this.
Users will need to use munge to create unique names for rack objects, eg: munge `keyid,id` = `keyid_id` key column name, or not use duplicate names in Netbox.

**Comment by sol1-matt** [comment]
Racks added in release [v3.6.1.0](https://github.com/sol1/icingaweb2-module-netbox/releases/tag/v3.6.1.0)
