### ISSUE TITLE
Sync rule stuck in loop of creating / deleting vars

### ISSUE THREAD

**Issue by jseifeddine** [sol1/icingaweb2-module-netbox#34]
So... we a sync rule 

![Screenshot 2024-05-28 at 10 59 17 PM](https://github.com/sol1/icingaweb2-module-netbox/assets/144011572/6bc26816-ebae-45a8-a619-a2a0d9ee9c4f)

It creates the object fine as expected, happy days. 

# Issue:
Subsequent syncs will remove `vars.tags`  

![image](https://github.com/sol1/icingaweb2-module-netbox/assets/144011572/0e4a9ba6-7137-489f-bf1f-98ac0064858a)

If you sync once again director shows modifications, even though it doesn't show what changed ( perhaps a clue to root cause of the issue ) 

![Screenshot 2024-05-28 at 10 53 31 PM](https://github.com/sol1/icingaweb2-module-netbox/assets/144011572/314a8079-51d8-4c71-a437-0940e8fc4875)

This loop continues indefinitely, every time the sync rule runs

Thank you for your contributions 🥇

**Comment by sol1-matt** [comment]
This is a director/config bug that occurs when when the value of `icinga_var` is `null`, it can be worked around using a filter.
However the filter also has a issue (#35) when the value of `icinga_var` is a `object` which is the most likely value other than `null`.

There needs to be a separate var so filter can determine what the value of `icinga_var` is.

**Comment by sol1-matt** [comment]
Solution added to [v3.6.1.3](https://github.com/sol1/icingaweb2-module-netbox/releases/tag/v3.6.1.3)
