### ISSUE TITLE
must be of type string, stdClass given | Empty config_context in NetBox

### ISSUE THREAD

**Issue by jseifeddine** [sol1/icingaweb2-module-netbox#35]
So we put a filter on `icinga_var` property 

![image](https://github.com/sol1/icingaweb2-module-netbox/assets/144011572/9ac328f0-d456-41c1-bb27-f444bec71240)

# Issue 
problem is, there are some objects in the import_source that don't have config_context defined

![image](https://github.com/sol1/icingaweb2-module-netbox/assets/144011572/5d316be4-79a0-44a6-abdb-1ccbc5c1aeee)

**Comment by sol1-matt** [comment]
This is a director limitation when using filters and trying to compare a object.

There needs to be a separate var so filter can determine what the value of `icinga_var` is.

**Comment by sol1-matt** [comment]
Solution added to [v3.6.1.3](https://github.com/sol1/icingaweb2-module-netbox/releases/tag/v3.6.1.3)
